### ISSUE TITLE
Working with normalized datasets

### ISSUE THREAD

**Issue by tengfei-emory** [zhangyuqing/ComBat-seq#2]
I suppose that we should input the raw count matrix instead of normalized count matrix to ComBat-seq so that the negative binomial assumption would satisfy. However, sometimes we may only obtain a normalized dataset, without raw count matrix. Are there any suggested strategies about how to apply ComBat-seq for that scenario? Thank you.

**Comment by zhangyuqing** [comment]
Hi @tengfei-emory, great question! Strictly speaking, ComBat-Seq should not be used in that scenario (and neither should edgeR or DESeq2), since the normalized data violate the assumptions under these methods. 

There's a thread on Bioconductor about using normalized counts in edgeR (https://support.bioconductor.org/p/65890/#65910), which I find similar to our discussion.

**Comment by tengfei-emory** [comment]
Thank you so much for the information!
